### PR TITLE
fix: replace in file working on os x

### LINKED ISSUE #2: [OS X] Issues initializing
Hiya 👋 

Neat package! I'm on os x, and am going to document some issues with installation.

`./laradose.sh --install`
- [ ] all project files get mutated
> diff --git a/.eslintrc.json b/.eslintrc.json
old mode 100644
new mode 100755

- [ ] Sed issues ( I assume these are because os x ships with a different sed than linux)

> sed: 1: "package.json": extra characters at the end of p command
Type the container number (again to uncheck, ENTER when done):
sed: 1: "./.env": invalid command code .
sed: 1: "./.env": invalid command code .
sed: 1: "./.env": invalid command code .
sed: 1: "./.env": invalid command code .
Linux User ID for file permissions (current user: 501): [1000] 501
sed: 1: "./.env": invalid command code .

### PR DESCRIPTION
**Pull request by mr-feek**
This seems to work on OS X. I'm no bash/perl expert, so please let me know what you think!

Fixes #2

### CODE REVIEW

**Comment by AdrienPoupa** [comment]
I like this. Could you maybe check if Perl is available before doing this, or running this only on OSX? https://stackoverflow.com/a/8597411/11989865

**Comment by mr-feek** [comment]
It was my understanding that perl should be available on the majority of linux distros since 2009 ([source](https://refspecs.linuxfoundation.org/LSB_4.0.0/LSB-Languages/LSB-Languages/perllocation.html)).

If we want to do a runtime check for operating system, we can do that but I might as well switch back to using `sed`, just changing the syntax depending on env. What do you think?

**Comment by AdrienPoupa** [comment]
You're right. I tested it and it works.

Just to be really safe, can you add a `verify_command` to be certain perl is there? https://github.com/AdrienPoupa/laradose/blob/master/laradose.sh#L278

**Comment by mr-feek** [comment]
Sure! I'll get to it later hopefully

**Comment by mr-feek** [comment]
hows that @AdrienPoupa ?

**Comment by AdrienPoupa** [comment]
Perfect, thanks!

**Pull request merged**
